<?php

define("FILE_UPLOAD_PATH",                                $_SERVER["DOCUMENT_ROOT"] . "/temp_image/");
define("REGIST_ITEM_QUERY",                               "insert into items (galaxyuserid, itemname, description, price, currency, locationtype, zipcode, state, city, latitude, longtitude, status) values (:GALAXYUSERID, :ITEMNAME, :DESCRIPTION, :PRICE, :CURRENCY, :LOCATIONTYPE, :ZIPCODE, :STATE, :CITY, :LATITUDE, :LONGTITUDE, '000')");
define("REGIST_IMAGE_QUERY",                              "insert into images (imageid, itemid, imagetype, imageurl) values (:IMAGEID, :ITEMID, :IMAGETYPE, :IMAGEURL)");
if (!defined("USER_EXIST_CHECK_QUERY_BY_ID")) {
	define("USER_EXIST_CHECK_QUERY_BY_ID", "select galaxyuserid from users where galaxyuserid = :GALAXYUSERID");
}
define("SEARCH_ITEM_BY_KEYWORD_ORDER_BY_LMDDESC_QUERY",   "select items.itemid, items.galaxyuserid, items.itemname, items.price, items.currency, items.locationtype, items.zipcode, items.state, items.city, items.latitude, items.longtitude, images.imageurl from items left join images on items.itemid = images.itemid and images.imagetype = 'THUMBNAIL' where items.itemname like :KEYWORD and items.currency = :CURRENCY and items.status = '000' order by items.lastmodifieddate desc");
define("SEARCH_ITEM_BY_KEYWORD_ORDER_BY_LMDASC_QUERY",    "select items.itemid, items.galaxyuserid, items.itemname, items.price, items.currency, items.locationtype, items.zipcode, items.state, items.city, items.latitude, items.longtitude, images.imageurl from items left join images on items.itemid = images.itemid and images.imagetype = 'THUMBNAIL' where items.itemname like :KEYWORD and items.currency = :CURRENCY and items.status = '000' order by items.lastmodifieddate asc");
define("SEARCH_ITEM_BY_KEYWORD_ORDER_BY_PRICEDESC_QUERY", "select items.itemid, items.galaxyuserid, items.itemname, items.price, items.currency, items.locationtype, items.zipcode, items.state, items.city, items.latitude, items.longtitude, images.imageurl from items left join images on items.itemid = images.itemid and images.imagetype = 'THUMBNAIL' where items.itemname like :KEYWORD and items.currency = :CURRENCY and items.status = '000' order by items.price desc");
define("SEARCH_ITEM_BY_KEYWORD_ORDER_BY_PRICEASC_QUERY",  "select items.itemid, items.galaxyuserid, items.itemname, items.price, items.currency, items.locationtype, items.zipcode, items.state, items.city, items.latitude, items.longtitude, images.imageurl from items left join images on items.itemid = images.itemid and images.imagetype = 'THUMBNAIL' where items.itemname like :KEYWORD and items.currency = :CURRENCY and items.status = '000' order by items.price asc");
define("GET_ITEM_DETAIL_QUERY",                           "select items.itemid, items.galaxyuserid, items.itemname, items.description, items.price, items.currency, items.locationtype, items.zipcode, items.state, items.city, items.latitude, items.longtitude, images.imageurl from items left join images on items.itemid = images.itemid and images.imagetype = 'IMAGE' where items.itemid = :ITEMID");
define("GET_RECENT_SELL_ITEM_QUERY",                      "select items.itemid, items.galaxyuserid, items.itemname, items.description, items.price, items.currency, items.locationtype, items.zipcode, items.state, items.city, items.latitude, items.longtitude, images.imageurl from items left join images on items.itemid = images.itemid and images.imagetype = 'THUMBNAIL' where items.galaxyuserid = :GALAXYUSERID and items.status != '001' order by lastmodifieddate desc limit 5");
define("GET_USER_COUNTRY_QUERY",                          "select country from users where galaxyuserid = :GALAXYUSERID");
define("ITEM_EXIST_CHECK_QUERY",                          "select itemid from items where itemid = :ITEMID");